### ISSUE TITLE
undefined function [get/is/has]articleId()

### ISSUE THREAD

**Issue by denbatte** [Kunstmaan/KunstmaanBundlesCMS#1075]
Hi guys,

I have created a custom pagetype and made an adminlist of it.
Now I want to add an extra row but the result says undefined function [get/is/has]articleId().
I probably did not join the right tables in my adapt query builder method?

Can anyone give me a pointer?

**Comment by jockri** [comment]
Are you using ORM AdminList? Then it is better to rename the `articleId` property with `article`.
Can you give some more context about your problem?

**Comment by virtualize** [comment]
Had the same issue a while ago. I think the reason is that your AdminListConfigurator is handling NodeTranslation entities (i.e. you inherit from [AbstractArticlePageAdminListConfigurator](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php)) and not your actual PageType entity, where your additional properties are defined.

**Comment by jockri** [comment]
When you want both information from NodeTranslation en Page entity, I suggest you use a DBAL adminlist, and write the whole query yourself.
