### ISSUE TITLE
Entity generator produces "not a valid entity or mapped super class" when generating an admin list

### ISSUE THREAD

**Issue by fcogutierrez** [Kunstmaan/KunstmaanBundlesCMS#110]
I tried generating a simple entity using the "kuma:generate:entity" console command and it produced this error: 

Class "Kunstmaan\SchedulerBundle\Entity\MeetingType" sub class of "Kunstmaan\AdminBundle\Entity\AbstractEntity" is not a valid entity or mapped super class.

I also asked to generate an admin list.

![screen shot 2015-01-21 at 11 38 12](https://cloud.githubusercontent.com/assets/8028313/5834897/61d28d5e-a162-11e4-93f0-6403caea2158.png)

**Comment by denbatte** [comment]
Hi,

Thank you for your bug report.

I have tried to reproduce your error with a fresh installation (following the getting started guide) of the bundles but I was unable to do so.

![screen shot 2015-02-09 at 17 00 48](https://cloud.githubusercontent.com/assets/505196/6109791/b14f3eb6-b07d-11e4-99b6-c2c04f5bb504.png)

Feel free to re-open a bug report with additional information if the issue is not solved.
