### ISSUE TITLE
Change minimum required characters in searchterm

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1253]
Hi,

I would like to know how I can override ElasticSearch's the default value of 3 in 'minimum_should_match' in KunstmaanSearchBundle.

I want to show results if a term is atleast 2 characters.

Thanks.

**Comment by sandergo90** [comment]
Hello,

You can override the node searcher class and change the defineSearch function.

Cheers,
Sander

**Comment by KevinSleegers** [comment]
Thanks for your answer, Sander.

I've managed to override the class, but I can't find a property that I can modify to return search results when the searchterm only consists of 2 characters.

Could you tell me where I can change that?

**Comment by sandergo90** [comment]
Hi,

In the definesearch function, the "setFieldMinimumShouldMatch" function is used. You can change the value at that place.

Cheers

**Comment by Numkil** [comment]
@KevinSleegers 

I just wanted to add that you will have to configure your own nGram analyzer as well to be able to search for word blocks of 2 characters. You can find information on how to configure the bundles to use your custom analyzer here https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/SearchBundle/Resources/doc/SearchBundle.md. 

I suggest extending the already implemented NGramAnalysisFactory and overriding the method addNGramTokenizer() with the following code. This in combination with setting the fieldMinimumShouldMatch will allow you to search for keys as small as 2 letters.


```php
    /**
     * @return AnalysisFactoryInterface
     */
    public function addNGramTokenizer()
    {
        $this->tokenizers['kuma_ngram'] = array(
            'type'     => 'nGram',
            'min_gram' => 2,
            'max_gram' => 30,
            'token_chars' => [ "letter", "digit" ]
        );
        return $this;
    }
```

Word blocks this small are kind of an exception in the bundles, which is why you have to do this extra work. The reason for this is that your search results will probably not be very good at all. For example searching for the word "code" will now return results for any word which has "co" or "od" or "de" in it. Like abode.

I hope this helps you somewhat further.

**Comment by sandergo90** [comment]
@jockri close
