### ISSUE TITLE
Language specific entity relationships and management

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#1267]
We have a multi-domain/multi language websites with some fairly vast relationships. A couple of times during this development process i have found myself skirting around the issue of language, but i don't think i can anymore! Let me give you an example;

This is the form builder for a multiple entity relationship pagepart (which works)

```
$builder->add('recipes', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', array(
            'label' => 'admin.pageparts.related_recipes.form.recipes.label',
            'class' => 'Superrb\AmysBundle\Entity\Pages\RecipePage',
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('a')
                    ->innerJoin('KunstmaanNodeBundle:NodeVersion', 'v', 'WITH', 'a.id = v.refId')
                    ->innerJoin('KunstmaanNodeBundle:NodeTranslation', 't', 'WITH', 't.publicNodeVersion = v.id')
                    ->innerJoin('KunstmaanNodeBundle:Node', 'n', 'WITH', 't.node = n.id')
                    ->where('t.online = 1')
                    ->andWhere('n.deleted = 0')
                    ->andWhere('v.refEntityName = :refname')
                    ->setParameter('refname', "Superrb\\MyBundle\\Entity\\Pages\\RecipePage");
            },
            'expanded' => false,
            'multiple' => true,
            'required' => false,
            'attr' => array(
                'placeholder' => 'admin.pageparts.related_recipes.form.recipes.placeholder',
                'class' => 'js-advanced-select form-control advanced-select',
            )
        ));
```

As you can see, this query is selecting the proper node translation, but the language is not specified. This is because it doesn't seem to be possible to select the Request object at this point in the form. 

I would want to add something like; 

```
->andWhere('t.lang = :lang')
              ->setParameter('lang', $lang);
```

in order to specify the language of results i need. 

In a similar situation, Entities and AdminListConfigurations don't seem to have access to the Request, so i cannot create any extra table columns to use to store the locale, so all the entities are available across all the multi-domain/multi-language setups with no language/locale specificity. 

Any direction on this would be much appreciated!

**Comment by mlebkowski** [comment]
If you’re using the container (registering your form types in the container) you always have the request, since there is the `request_stack` service. Similarly in the `AdminListConfigurators` — they are created in the controller, there’s nothing stopping you to pass additional services in the constructor. [For example](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php#L25):

```php
$this->configurator = new RedirectAdminListConfigurator(
    $this->getEntityManager(), 
    null,
    $this->get('kunstmaan_admin.domain_configuration')
);
```

You could instead use `$this->get('request_stack')->getCurrentRequest()`, etc.


But it’s a common task — selecting a published page of given type, limited to given site and language. So I created [`NodeEntityType`](https://github.com/syzygypl/kunstmaan-extra-bundle/blob/master/src/Form/NodeEntityType.php) — it extends the `EntityType` so you need only to provide the class name, and it’s automatically selected amongst all published nodes in given tree and language. It’s very similar to your code with some exceptions:

 * It filters via left & right — this is to ensure that all pages are subpages of given node (by default the current root node)
 * filters by lang (by default the current language, calculated by a separate service in my case)
 * The class name can be provided in a short form, called [Content Type](https://github.com/syzygypl/kunstmaan-extra-bundle/blob/master/src/Resources/doc/content-type.md) — you can skip this, it’s only convenience

This form is [registered in the container](https://github.com/syzygypl/kunstmaan-extra-bundle/blob/master/src/Resources/config/form_types.yml#L7-L15), this way it always has access to its dependencies. 


Feel free to use my bundle or copy and adapt the code to your needs. :)

**Comment by alexborton** [comment]
Thanks @mlebkowski - the above is really helpful.

I have managed to implement site/lang specific filtering and management of Entities using an extra locale column and populating via the current request (request_stack) passed through the original configurator as you suggested above. 

I am still struggling to apply this logic to a form for a article page. 

I have a News page that has a selection of categories (separate entities) to select from. So the form builder (currently) looks like this;

```
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder->add('categories', EntityType::class, array(
            'label' => 'admin.pages.news.form.categories',
            'class' => 'Superrb\MyBundle\Entity\NewsCategory',
            'expanded' => false,
            'multiple' => true,
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('a')
                    ->where('a.locale = :locale')
                    ->setParameter('locale', 'en_us');
            },
        ));
        $builder->add('coverImage', MediaType::class, array(
            'label' => 'admin.pages.news.form.cover_image',
            'pattern' => 'KunstmaanMediaBundle_chooser',
            'mediatype' => 'image',
            'required' => true,
            'constraints' => array(new Assert\Media(array(
                'mimeTypes' => array('image/jpg','image/jpeg',),
            ))),
        ));
    }
```

You can see the parameter for local is set manually. I have no idea of accessing the request from this point. Sorry if it seems i am repeating myself here, i am fumbling my way through a little! Thanks in advance
