### ISSUE TITLE
[MediaBundle] Bug: image chooser does not work anymore.

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1367]
Hello, after an upgrade to I have noticed that image chooser on rich text editor does not work anymore.

When I select an image, a token is taken as a value instead of image URL. This is the cause https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1225/files#diff-79fef42617236c3caeca65fbf0331b7cR212

![screenshot](https://sc-cdn.scaleengine.net/i/e5c7ecc668e0feeadfc46f65ee032a0b.png)

Same with link chooser:

![screenshot](https://sc-cdn.scaleengine.net/i/c26e53595e869b6647504a46dd728b1e.png)

**Comment by sandergo90** [comment]
Hi,

That is how it is supposed to work. If you read the changelog you will see that you need to pipe URL output in your twig to | replace_url. Then this token will be replaced by the URL.

**Comment by aistis-** [comment]
@sandergo90 thanks for the quick response. But this content is persisted to the database. So it in the end it is just:

```
<div class="message-or-whatever">{{ message.content|raw }}</div>
```

the field contains already formed HTML body. Where exactly do you suggest using `replace_url`? I believe `/home/wut/Projects/crowdhouse/www/vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js` is taking `data-path` and pasting it directly to Rich editor :thinking:

**Comment by sandergo90** [comment]
The twig should contain:

<div class="message-or-whatever">{{ message.content|replace_url|raw }}</div>

**Comment by aistis-** [comment]
It works that way, but I found some other cases:
- on the admin field editing window, the image is not show https://sc-cdn.scaleengine.net/i/3f2523d50e3193234ce42feb45e3cb68.png
- so everywhere where this field is rendered in the front end, I have to use this extra `replace_url` filter instead of just rendering a raw content

**Comment by sandergo90** [comment]
Hi,

Yes that's correct. Every pagePart that contains URL tokens need to be passed to the replace_url function. You're first question is correct indeed. You can create an issue for this only.

Cheers

**Comment by aistis-** [comment]
I am thinking that rendering these kind of fields, it must be under one filter only like `{{content|wysiwyg_field}}` where under the hoot all required filters (`raw` and `replace_url` at the moment) would be attached. So when we had the third or forth filter necessary to correctly render the wysiwyg field, we would not to change API in twig anymore.

Do you have any suggestions to workaround the [this](https://sc-cdn.scaleengine.net/i/3f2523d50e3193234ce42feb45e3cb68.png)?

**Comment by sandergo90** [comment]
Yeah that would be an excellent solution indeed.

I think we need to look into the ckeditor javascript. There maybe is a javascript function that we can change to replace the url. Don't know for the moment.

**Comment by aistis-** [comment]
Thanks for the answers, for a temporary workaround - I just added the filter to the twig for end users. Our admins somehow will have to live with this for a while :)

**Comment by sandergo90** [comment]
Lol, indeed! We will fix it when we have the time ;)

**Comment by mtnorthrop** [comment]
I've run into this bug as well since upgrading to v4. Since clients are used to adding images directly into the rich text editor, it would be nice if this was still an option.

In other threads, I've read that Kunstmaan's position on this is that it's better to use page parts to add images instead of inserting them into the rich text editor, but in our case the RTE is being used in an admin list and I don't know of a way of using page parts inside of an admin list item (I think I'll open a new issue to ask whether there's a correct way of doing this.)

**Comment by sandergo90** [comment]
Hi @mtnorthrop ,

Did you read the comments in this issue about adding the replace_url twig function ?

Sander

**Comment by mtnorthrop** [comment]
Hello @sandergo90 ,

Thanks for your reply; I did read about the replace_url twig function and it worked perfectly to get the images to display on the frontend, but the issue that I have is just with the images displaying in the rich text editor.

Since it looks like Kunstmaan is not interested in supporting this (and I understand and respect the reasoning behind this), I'm now looking for a way of using page parts in admin list items so that I can give users a way to mix rich text and images in admin list items without having to insert them through the rich text editor.

**Comment by Devolicious** [comment]
@mtnorthrop I Answered your question in https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1431

Happy coding!

**Comment by mtnorthrop** [comment]
Thanks for the answer, I really appreciate it!
