### ISSUE TITLE
[ConfigBundle] InternalName always null

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1418]
Hi,

Recently I've created a new project with Kunstmaan 4.0 because I wanted to use the new ConfigBundle functionality.

I've followed all the steps in the documentation, and have had no trouble creating the entity and form type. The problem I'm facing right now is that my internalName (the param in indexAction of ConfigController.php) always returns 'null'.

Note; I am using a singlelang website so in the routing I have set the prefix (in kunstmaan_config) to always use /nl/).

Does anyone know what I might be doing wrong?

Thanks in advance,
Kevin

**Comment by adrianwaler** [comment]
Hey,

I discovered it today when I wanted use this bundle. 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/0cd02390dacbf1ae997f7d351d7bc3bc0ee38696

Variable name was changed from internal_name to internalName in indexAction, but in routing and view still is internal_name.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/ConfigBundle/Resources/config/routing.yml#L2

This is not your fault and it should be fixed in ConfigBundle.

**Comment by KevinSleegers** [comment]
Thanks, it is working fine now! 👍
