### ISSUE TITLE
[AdminList] Question: Is it possible to use page parts in an AdminList item?

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#1431]
Is it possible to use PageParts in an AdminList item, and, if so, what is the correct approach to implement this?

The reason I'd like to do this is because I have AdminList items with rich text fields that we need to insert images into. Since the changes to the URL Chooser in v4, inserting images into the rich text editor is a bit broken (see #1367).

I've read in other threads that Kunstmaan's position on this is that we should add images as page parts, and not by inserting them into the rich text editor, so now I'm looking for a way to set up page parts in my AdminLists so that users can mix text and images in an AdminList item.

If anybody has any pointers on how to set this up, I'd be very grateful!

**Comment by Devolicious** [comment]
Hi @mtnorthrop,

When we have such a need we tend to use pages in an adminlist. Main reason why we do it like this is because everything is already setup properly. Our ArticleBundle is a good starter example for this.

That being said, you could attempt to add pageparts to a normal Entity with a ```kunstmaan_admin.adaptSimpleForm``` event and do something like this in the eventlistener:

```php
$data = $event->getData();

if ($data instanceof HasPagePartsInterface) {
    $tabPane = new TabPane(
        'your_identifier',
        $event->getRequest(),
        $formFactory
    );

    $pagePartAdminConfiguration = new SomePagePartAdminConfigurator();
    $somePagePartWidget = new PagePartWidget($data, $event->getRequest(), $this->em, $pagePartAdminConfiguration, $this->pagePartAdminFactory);
    $somePagePartWidget->setTemplate('AcmeBundle:Something:default.html.twig'); //optional

    $formWidget = new FormWidget();
    $formWidget->addType('Form', $event->getFormType(), $data);
    
    $tabPane->addTab(new Tab('AdminForm', $formWidget), 1);
    $tabPane->addTab(new Tab('Pageparts', $somePagePartWidget), 2);
    
    $tabPane->buildForm();
    $event->setTabPane($tabPane);
}
```

This is an example of how it **might work**. Never attempted to do it this way so it will probably need some tweaks but it's a start.

**Comment by mtnorthrop** [comment]
Hello @Devolicious ,

Thanks very much for the hint; it's saved me a lot of time. I'll have a look at how things are done in the ArticleBundle.
