### ISSUE TITLE
Ordering of node tree branches breaks when there are more than 50 pages.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#1466]
Version: 3.6.1

If you have more than 50 pages in a branch of a node tree you can no longer order the pages. Saving a page causes the page to jump to the first position in the branch.

This appears to be because the 'weight' field for the 'menunodetranslation' part of the form has a maximum value of 50. Any weights higher than 50 are being reset to -50 when you save the page and hence putting it first in the list.

I can't see an easy way of overriding this field to an integer field and allowing a much greater range of values. This is a problem for us where there are a lot of sub pages that don't appear in main navigations for example a blog or a products listing (https://www.amys.com/our-foods)

Can you guys advise on whether this can be easily overridden, or if the field can be changed to allow a greater range of values.

Thanks

**Comment by mlebkowski** [comment]
It’s not easy or pretty but doable:

```php
class NodeTranslationMenuAdopter implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            Events::ADAPT_FORM => 'onNodeTranslationMenu'
        ];
    }
    public function onNodeTranslationMenu(AdaptFormEvent $event)
    {
        $tabPane = $event->getTabPane();
        foreach ($tabPane->getTabs() as $tab) {
            if ("Menu" === $tab->getTitle() && $tab instanceof Tab) {
                $widget = $tab->getWidget();
                $types = $widget->getTypes();
                if (isset($types['menunodetranslation'])) {
                    $widget->addType('menunodetranslation', new NodeMenuTabTranslationAdminType(), $event->getNodeTranslation());
                }
            }
        }
    }
}
```

I agree that this should be changed. I don’t see why there even is such a field there, since the nodes can be reordered in the tree.

**Comment by Devolicious** [comment]
Hi @iknowfoobar & @mlebkowski,

I know, it's legacy for ordering the nodes and it hasn't changed since we can order them in the three. Now mostly we would create an adminlist when dealing with a lot of nodes so we don't have to order them in the tree. But I talked it over with @jockri yesterday an yes it should change and we will come up with a beter solution for this.

Now my suggestion would be to create a FormTypeExtension where you would override the weight to a plain integer field instead of a range. Than you don't have to mess with an eventlistener and checking if you're on the correct tab and such. If for some reason an extension doesn't work, @mlebkowski's suggestion would be the next step.

**Comment by mlebkowski** [comment]
👍  Form Type Extension!

My solution was from an earlier bundles version, where the `NodeMenuTamBranslationAdminType` (responsible for the `weight` field) was not registered in the container. This was in Symfony 2.6, and forms were referenced by custom names instead of class names, and I think that prevented the extension from working. I think… ;)

**Comment by iknowfoobar** [comment]
Thanks guys, I hadn't used Form Type Extensions before. Very useful. All working now!
