### ISSUE TITLE
Saving data as new in title, name field, always save 1 number

### ISSUE THREAD

**Issue by ismaserrano** [Kunstmaan/KunstmaanBundlesCMS#1485]
Hi!

It's a rare behavior. When I create a new entity, for example with title, description and media, if I add new data from the form, always as new, the title field saves '1' number... the form submit the correct data, but I don't know why saves '1' number. When I edit the content and modify the title, the data saves well.
I can't explain me!

Can anyone help me? Thank you!

**Comment by Numkil** [comment]
Did you generate an adminlist for this entity? This behavior happens when generating an adminlist for an entity and configuring the adminlist to be sortable based on a string instead of id. In your case probably you thought you could use the title field for sorting your adminlist. You will have to turn revert this configuration and just let it be sortable based on id. This is a bit confusing about adminlists and something we should improve upon.

**Comment by ismaserrano** [comment]
Yes!! That's it! A lot of thanks!
