### ISSUE TITLE
User Entity not customizable?

### ISSUE THREAD

**Issue by mablae** [Kunstmaan/KunstmaanBundlesCMS#1518]
I have the need to extend the user entity `KunstmaanAdminBundle::User`` with more fields. 

Any idea how to achieve this?

**Comment by deZinc** [comment]
Have a look at this:
https://bundles.kunstmaan.be/news/extending-the-admin-user-entity

That should work and solve your problem.

**Comment by mablae** [comment]
Thanks alot! I must have overlooked that, sorry

**Comment by mablae** [comment]
@deZinc I did exactly that already, but it leaves an empty `kuma_users` table due to automapping

**Comment by mlebkowski** [comment]
just FYI, you probably don’t need to extend the user entity. I once thought I do, and I ended with `acme_users` (extended) and an empty `kuma_users` tables. In another project, I just created another table, for example `user_profiles` with one-to-one relation.

**Comment by mablae** [comment]
@mlebkowski And how to map that 1:1 relation? 😄 It's the same problem still. 
And generated User class in the Userland Bundle would  solve this problem the right way. Make BaseUser an `MappedSuperClass`

But the current workaround works for me, I can live with the empty `kuma_userrs` table

**Comment by mlebkowski** [comment]
Let’s assume we want to extend the user with `Profile` information: name, surname, phone number, whatever. First of all, those fields do not belong to the `User` entity according to the database normalization rules. You can easily map `Profile` to `User`, because `Profile` is under your control and you only need to map one side of a relation. And even if it weren’t you can still do it programatically. First google hit on that topic:

https://www.theodo.fr/blog/2013/11/dynamic-mapping-in-doctrine-and-symfony-how-to-extend-entities/

What you actually lack is a convenient getter on the `User` entity. I used a service to fetch user’s profile instead. It’s as simple as this:

https://gist.github.com/mlebkowski/5b3bf74ad795f20005000b746045e064

**Comment by mablae** [comment]
@mlebkowski Thanks for the Links!
