### ISSUE TITLE
Improve routing performance

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1567]
After profiling with blackfire i noticed that the match method in https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php#L75 is called twice for each request. So the node translation etc is also called twice. Maybe we can improve this for better performance?

![screen shot 2017-07-31 at 19 45 45](https://user-images.githubusercontent.com/1218389/28790355-098df9fa-7629-11e7-839f-fdacacf5771e.png)

**Comment by delboy1978uk** [comment]
![image](https://user-images.githubusercontent.com/2684575/33319089-6d415ccc-d43d-11e7-8e79-6b9e432c293e.png)

Looks like the router is called twice due to the Symfony LogoutListener :
```php
return $this->httpUtils->checkRequestPath($request, $this->options['logout_path']);
```
What we could do is put the translation nodes in an array property, and then instead of fetching twice, we can check if we set and 'cached' it in the array. What do you think?

**Comment by delboy1978uk** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1711

**Comment by Numkil** [comment]
Closing because improvement has been merged. Listener will still be called twice but doctrine result is cached and not called twice.
