### ISSUE TITLE
[RedirectBundle] It is possible to create duplicate records

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1745]
It is possible to create multiple redirects with the same origin. Should we define a constraint for this?

**Comment by delboy1978uk** [comment]
Hi, I just checked the behaviour. You can indeed add two redirects with the same origin, and of course this means the chained router returns the first match, so the second redirect will never work. 
I'll put a check in place to ensure that we can't do this!

**Comment by Numkil** [comment]
@dannyvw 
I am closing this ticket because the related PR has been merged. the uniqueconstraint on (domain, origin) combination was not working when domain was null as was the case in single domain websites. Redirects that are already saved need to be deleted and readded so that the domain field will be filled in properly in the database. 

If you are experiencing any other problems do not hesitate to reopen the issue.
