### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1751]
When will 5.0 released? And will this release be fully compatible with Symfony 3.4?

**Comment by Devolicious** [comment]
Hi @dannyvw,

We've been struggling with the v4 and v5. There is one big PR that is going to be discussed internally, namely #1742. After that RC2 of v5 is going to be released so we can do a short stabilization period and then we will release v5, along with v4.0.3 and v4.1. And yes, we are locking v5 on SF 3.4 because it will give us the opportunity to use the latest and greatest of what symfony has to offer. So there is no doubt about it being compatible.

Cheers.

**Comment by dannyvw** [comment]
@Devolicious Any idea when the release date is?

**Comment by Devolicious** [comment]
@dannyvw, the release is now scheduled at 30/01/2018 but it might be sooner than that if we see that everything is running without issues.

**Comment by dannyvw** [comment]
@Devolicious Thanks for the information! We will update soon :)
