### ISSUE TITLE
+ signs are removed from wysiwyg fields

### ISSUE THREAD

**Issue by wesleylancel** [Kunstmaan/KunstmaanBundlesCMS#1863]
Not sure if this is related to #1857 in any way, but it seems + signs are removed from wysiwyg fields before they are saved.

**Comment by mtnorthrop** [comment]
I've done a quick check on 5.0.5 and plus signs seem to be working for me. Would you be able to give me an example of the exact string that isn't working? 

I've just tried saving a + sign by itself (typed directly, not pasted) and it seems to work ok.

If we can't replicate the issue and you think this might be a problem with the data transformer that's attached to the field, would you be able to create a failing test, maybe in `Kunstmaan\AdminBundle\Tests\Form\MediaTokenTransformerTest` on the 5.0 branch?

Since I was just working with this recently, I'd be happy to try to produce a fix if we can pinpoint the problem

**Comment by wesleylancel** [comment]
@mtnorthrop Thanks for looking into this. I somehow missed that my project was on 5.0.3, bug seems to be fixed in 5.0.5.

**Comment by mtnorthrop** [comment]
@wesleylancel No problem, I'm glad the upgrade fixed it.
