### ISSUE TITLE
Implementing live suggestions elasticsearch

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1876]
Hi,

I've been looking into implementing live suggestions into our existing Elasticsearch search functionality within a Kunstmaan 3.6 project. I've found quite a simple guide on how to do this when using the friendsofsymfony/elastica-bundle (https://www.codevate.com/blog/14-implementing-search-as-you-type-autocomplete-with-elasticsearch-and-symfony), but Kunstmaan is not using that. 

I was wondering if anyone has implemented this successfully, and would be so kind to let me know how to get started on this. For instance, the config.yml for Elasticsearch seems to be different in Kunstmaan.

Thanks,
Kevin

**Comment by sandergo90** [comment]
@KevinSleegers 

We are indeed not using the friendsofsymfony/elastica-bundle but our doing our own integration with ruflin/elastica. 

I read the tutorial you want to follow and this can easily be done with the bundles. You can also create analysers, suggestions, ...

Take a look at the KunstmaanNodeSearch bundle to see what you can do with it.

Cheers

**Comment by Devolicious** [comment]
Hi @KevinSleegers,

Nice post about auto suggestions in elasticsearch. However, the reason we don't use the FOS elastica is because it's kind of the same thing as our `KunstmaanSearchBundle` and `KunstmaanNodeSearchBundle`. We have a more advance implementation because of the Node system that is being use in the cms instead of simple entities that you can use with FOS. Nonetheless, that doens't mean that this is not possible. You can overwrite the default configuration, mapping and analyses. Just checkout the `NodePagesConfiguration` class and the dependency injection in the `KunstmaanNodeSearchBundle` to start overwriting the elasticsearch config.

**Comment by KevinSleegers** [comment]
Hello @Devolicious @sandergo90,

Thanks for the reply! I will definitely look into the KunstmaanNodeSearchBundle.
