### ISSUE TITLE
[NodeBundle] BC Break NodeMenuItem

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1888]
In version 4.0 method "getLang" is removed from "NodeMenuItem". This is an public method which was not deprecated. Can you restore this or give an upgrade path? 

Method removed in commit: https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/3eb66d60d91a27594828f7c4a2f8264d98d34ad3#diff-61b24c90eb764c1c45273d592f482f90

**Comment by treeleaf** [comment]
Hi @dannyvw, 
we do not support (bug) fixes to 4.0 anymore. Even though it was not deprecated, it was removed with the release of 4.0

We can help you to find a way to upgrade your code. Can you give an example of the code that you would like to upgrade?

**Comment by dannyvw** [comment]
@treeleaf So removing public methods can be done in all versions without any notice? This will always break your code.

I already checked for any possibility to upgrade our code, but we need the getLang method on the NodeMenuItem.

**Comment by Devolicious** [comment]
@dannyvw, no the removing of public methods (BC Breaks) is not done in just any version. Only in a major release. You're right about the deprecation notice though, it should have been there in version 3.6. 

We only started to implement our PR policy where it's very clear what type of code submissions should go to which branch since the release of V4. Anyway, I recommend to upgrade to V5 instead since this is our supported version as from January 2018. With all the changes we made regarding our policy we're trying to make upgrades as easy as possible so that the community can stay updated with all the latest features.

Regarding your problem, how is it possible that you're not able to use the `getLocale` method on the NodeMenu itself? This was an unused method and it seems to be an edge case that could be solved otherwise. I'm gonna close the PR for now. We can reopen if there is a good reason for it. If you could provide us with some code snippets like @treeleaf asked, we might be able to help with this.

**Comment by dannyvw** [comment]
@Devolicious We are upgrading to version 5 (from 3.5).

We check of the input is an instance of `Node`, `NodeTranslation` or `NodeMenuItem` because of a custom implementation for generating translation urls. If we can add a getter `getMenu` on `NodeMenuItem` then we can solve our problem also (because `getLang` was only a proxy method). I don't have any other code snippets for this issue.

**Comment by Devolicious** [comment]
Hi @dannyvw, I assume that this is no issue anymore so I'm gonna close this. If not, let us know.

**Comment by dannyvw** [comment]
@Devolicious This is still an issue (BC break) in the core of Kunstmaan. We re-added the method in our fork to fix this, but this can't be a permanent solution.

**Comment by Devolicious** [comment]
We'll look into it

**Comment by acrobat** [comment]
@dannyvw Can you check PR #2639, it seems that this method was indeed incorrectly removed!

**Comment by dannyvw** [comment]
@acrobat Done, thx!
