### ISSUE TITLE
Installation Docs

### ISSUE THREAD

**Issue by hackzilla** [Kunstmaan/KunstmaanBundlesCMS#1988]
I discovered this project yesterday, and it looks exactly what I'm after.

However, I'm struggling to get started using the [installation instructions](http://kunstmaanbundlescms.readthedocs.io/en/latest/installation/#installation).
I've run into #1926, which is fixed with #1987

More importantly, I can't figure out why services aren't getting injected.

> [2018-05-28 18:59:50] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Too few arguments to function FOS\UserBundle\Controller\ChangePasswordController::__construct(), 0 passed in /Users/danielplatt/Sites/ofdan/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 195 and exactly 3 expected" at /Users/danielplatt/Sites/ofdan/vendor/friendsofsymfony/user-bundle/Controller/ChangePasswordController.php line 40

**Comment by acrobat** [comment]
Great that this project is exactly what you are looking for, but it looks like you didn't have the best experience during the project setup. All these issues are resolved or in the proces of being fixed but not yet released. 

More specific on the issue with the FosUserBundle, this was fixed in #1922. You can fix this for now (until the fix is released) by adding this requirement, `"friendsofsymfony/user-bundle": "2.0.*"` to your `composer.json`. This will install a version that is compatible with the kunstmaan cms and should resolve the issue you're having!

**Comment by hackzilla** [comment]
@acrobat I can't create the homepage.  
The button "Add Homepage" doesn't do anything.

I'm guessing an event isn't attaching.

**Comment by hackzilla** [comment]
Turns out it was a partial db import.
