### ISSUE TITLE
Deprecate service method in pages

### ISSUE THREAD

**Issue by denbatte** [Kunstmaan/KunstmaanBundlesCMS#211]
@Devolicious  http://symfony.com/doc/current/book/internals.html

**Comment by JoakimLofgren** [comment]
I make use of the service method to get the container in pages to be able to make custom behaviour in different pages. So if you want to deprecate it please provide a different solution which allows you to DIP in things.

**Comment by kimausloos** [comment]
@JoakimLofgren don't worry, we're deprecating this but the service method will continue to work as before. We'll replace it with a (much cleaner) controller as a service solution.

**Comment by JoakimLofgren** [comment]
Will that extend to page parts as well? That would be nice.

**Comment by Devolicious** [comment]
@JoakimLofgren The service method will not be removed (or not in the near future). We will still keep this as a default fallback. 

We are going to implement an eventlistener (http://symfony.com/doc/current/book/internals.html#kernel-controller-event) to bypass the slugcontroller. This will be activated by a new interface that has to be implemented on the page entity. With this interface we require the method getControllerAction() to return a callable string.

To answer your previous question: No. Why? Mainly because page parts are meant to be a rendering of a template with some data without any logic to it. On occasion it will happen that you need some sort of logic for a pagepart. There are 2 ways to achieve this:
1. Twig Extension functions when you don't need a different caching strategy
2. By using the ``` {{ render_esi(controller('bundle:controller:action')) }} ```. This way you prevent only that part of the view not being cached by varnish instead of the entire view.
