### ISSUE TITLE
Add up and down buttons to move pageparts, and move subentities in pageparts

### ISSUE THREAD

**Issue by krispypen** [Kunstmaan/KunstmaanBundlesCMS#216]
We can add move up and move down buttons to the left of the delete button of each pagepart and each subentity. This is because when pageparts are too big, the drag-and-drop is almost unusable

**Comment by wimvds** [comment]
An up/down button does not solve the issue imho, since the pagepart will be moved after a click on the button, you will have to scroll again and click on the button again if you want to move it more then 1 position up (or if auto scrolling was implemented it would be quite slow to reorder). I think a toggle button (per region?) to minify pageparts to 1 line which you can drag/drop would be both easier to implement and more user friendly. For pageparts containing sub entities you could add a similar button to minify the subentities in the containing pagepart for easier drag/drop reordering.

**Comment by IbeVanmeenen** [comment]
A button to minify layout is in my opinion a good idea, not only for subentities, but also for the pageparts in general.

**Comment by tentwofour** [comment]
+1 

A minify all within a region would be handy.

Up/down would temporarily fix drag/drop issues, even if it means scrolling back up. In that regard, a simple $(el).offset() call on the page part that was moved, and auto-scrolling the window to its new position might be feasible?
