### ISSUE TITLE
Errors when dumping assetic

### ISSUE THREAD

**Issue by WADStefan** [Kunstmaan/KunstmaanBundlesCMS#259]
Hey again guys,

Thanks for the quick response and swift resolution of the installation issue I was having.

Everything installed like a charm now. The admin backend is working.
I'm left with one issue when trying to dumping assetic.

Before dumping assetic I ran into a problem installing npm:
![image 069](https://cloud.githubusercontent.com/assets/11782618/6980722/cf8e7fc0-d9f6-11e4-9805-3d861aab52b8.png)

I don't know if it's related to the assetic dump issue here:
![image 068](https://cloud.githubusercontent.com/assets/11782618/6980730/ef8a2964-d9f6-11e4-8265-7104ca7207e6.png)

Regards,

Stefan Van den Heuvel

**Comment by tentwofour** [comment]
I'll go out on a limb ;)

Unless you doctored that CLI output, or your path to your project is actually '/path/to/project', I'd guess that npm can't find that path.

Try running npm install from the directory that contains the package.json file - the assetic dump issue is likely due to uglifyjs not being installed.

Hope that helps (albeit a bit late)
