### ISSUE TITLE
Upgrade imagine/imagine constraint in composer.json

### ISSUE THREAD

**Issue by wesleylancel** [Kunstmaan/KunstmaanBundlesCMS#2842]
Currently required at ~0.6 however version 2.4.0 of liip/LiipImagineBundle only supports ^1.1, meaning that can't be upgraded at the moment. Is there any specific reason to stay at the currently required version?

**Comment by acrobat** [comment]
I don't think there is specific reason for the `0.6` requirement, so I could be possible to upgrade the required version. The only thing that need to be checked that the current workaround for on the fly extension conversion still works (and there is 1 deprecated class that uses an imagine interface, so that should also work until the 6.0 release)
