### ISSUE TITLE
why is FormPageViewDataProvider final?

### ISSUE THREAD

**Issue by jerome2710** [Kunstmaan/KunstmaanBundlesCMS#3263]
I would like to create a page with both a form and some additional context from a custom ViewDataProvider. Our usual setup is:

```php
abstract class AbstractFormPage extends AbstractPage
{
    public function getViewDataProviderServiceId(): string
    {
        return FormPageViewDataProvider::class;
    }
}
```

```php
class SomePage extends AbstractFormPage
{
    public function getViewDataProviderServiceId(): string
    {
        return SomePageViewDataProvider::class;
    }
}
```

However, with `\Kunstmaan\FormBundle\ViewDataProvider\FormPageViewDataProvider::class` being final, my `SomePageViewDataProvider::class` can't extend the FormPageViewDataProvider to add the form-context. Any reason why it is declared final?

I've now injected `FormPageViewDataProvider` as a service in my `SomePageViewDataProvider`, calling;

```php
public function provideViewData(NodeTranslation $nodeTranslation, RenderContext $renderContext): void
{
    $this->formPageViewDataProvider->provideViewData($nodeTranslation, $renderContext);

    ....
```

but this feels cumbersome.

**Comment by jerome2710** [comment]
Any updates regarding this issue?

**Comment by acrobat** [comment]
Hi @jerome2710, sorry for the late answer! Regarding the final classes, this is a decision made to ease the maintainability of the code. In the past all classes where open to extension or had public properties/methods anyone could use and this made it hard to do required refactorings to improve our code base or add compatibility for newer symfony versions without breaking backwards compatibility.

That's why we decided to mark certain classes as final to allows us to make changes easier in the future. I understand this makes some cases a bit harder but in this specific case it doesn't make it impossible as you are able to insert the cms provider service into your and extend/change the resulting object yourself.
