### ISSUE TITLE
security.token_storage is now private

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#3350]
We have upgraded our site, currently on 7.1.x-dev,  but ran into a problem in the AbstractEntityArticle AdminListController in the ArticleBundle, where `security.token_storage` is no longer in the container.
![image](https://github.com/Kunstmaan/KunstmaanBundlesCMS/assets/2684575/7ada40e6-dc5a-492e-8831-92fde62d0991)
The service was made private in v6 of Symfony https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.0.md?plain=1#L459 

I have since tried on a fresh Kuma install using 7.1 of both the cms-skeleton and the bundles. 

When I access `/nl/admin` for the first time, I get the following error:
<img width="1048" alt="image" src="https://github.com/Kunstmaan/KunstmaanBundlesCMS/assets/2684575/b6be9d0d-eafa-46dc-86dc-7d4e50628122">

I tried to make the token storage public, both via yaml and via compiler pass, but neither successfully worked for me. I'm guessing anywhere that references it will need to use dependency injection instead?

**Comment by acrobat** [comment]
I can't reproduce this problem. When I debug a local demo app and set a breakpoint in the `AbstractArticleEntityAdminListController`, I can retreive the token storage service and get the user object

<img width="1398" alt="image" src="https://github.com/Kunstmaan/KunstmaanBundlesCMS/assets/1374857/aead877e-5370-41e6-927d-7ae3fe4e542b">

Which versions of symfony and the security bundle have you installed? Do you have any service overrides for the `AbstractArticleEntityAdminListController`? Because the controller uses a service locator it should not matter if the service is private.

**Comment by delboy1978uk** [comment]
As I mentioned, I also get this error on a fresh Kuma install using the 7.1 branches of the skeleton and the bundles, so there isn't anything overriding the config. The version of Symfony installed is `6.3.12`, as is the security bundle, and it was running on PHP `8.1`.

**Comment by jverdeyen** [comment]
@acrobat You can close this issue, since this is resolved on our side.

We've created a custom AdminlistConfiguratorBuilder which is used to create dynamic AdminlistConfiguration/Controller services in a CompilerPass. But we needed to add the service subscriber tag to the controller as automagic tagging from the AbstractController class seems to be ignored (or created later than the automagic tagging)

```
$definition->addTag('container.service_subscriber');
```

Thanks!
