### ISSUE TITLE
Error on cms-skeleton install 7.1 branch

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#3384]
My work colleague was trying to do a fresh Kuma skeleton install using the 7.1 branches in order to verify that he could reproduce the error I reported in https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/3350 .

However, now, upon the composer install, once it got to clearing cache, the following error occurred:

```
The service "sensio_framework_extra.controller.listener" has a dependency on a non-existent service "annotation_reader".
```
So we were unable to get as far as I did in the other issue in order to verify.

**Comment by acrobat** [comment]
That's because 7.1 still has a dependency on sensio/framework-extra-bundle (this dependency is removed in 7.2 and available in the 7.x branch, see #3378) because it uses annotations. In the default symfony 6.4 framework bundle annotations support is disabled by default, see https://github.com/symfony/recipes/blob/main/symfony/framework-bundle/6.4/config/packages/framework.yaml#L5. 

So to make it work you need to switch `framework.annotations: true`

**Comment by delboy1978uk** [comment]
thanks for clarifying! :-D
