### ISSUE TITLE
[MediaBundle] Media chooser preview not shown

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#464]
When you create a new pagepart with a media field type, and you select a pdf, the default thumbnail is not shown.

![screenshot 2015-06-02 14 11 17](https://cloud.githubusercontent.com/assets/517574/7935462/787c8154-0931-11e5-9adb-0c0db6bc4080.png)

**Comment by krispypen** [comment]
don't think we support previews for pdf's?

**Comment by jockri** [comment]
I think we support it, but if the pdf preview is not available, the default icon should be shown.

**Comment by LiesbethVanaerschot** [comment]
The default icon doesn't appear because we never enter the first part of the if statement... It always shows the else - part. Can we check on something else then 'value.ent'?

![screen shot 2016-02-15 at 15 54 30](https://cloud.githubusercontent.com/assets/6680787/13052080/0812ab9a-d3fd-11e5-98f3-5d2ec7910e3b.png)

![screen shot 2016-02-15 at 15 55 16](https://cloud.githubusercontent.com/assets/6680787/13052061/f7eed45a-d3fc-11e5-8000-01c32eef456d.png)

![screen shot 2016-02-15 at 15 55 01](https://cloud.githubusercontent.com/assets/6680787/13052088/10e3df64-d3fd-11e5-98d6-7ad8d16785e0.png)

**Comment by dbeerten** [comment]
This is merged, so it may be closed. @diskwriter
