### ISSUE TITLE
Cannot generate a bundle with app/console kuma:generate:bundle

### ISSUE THREAD

**Issue by ltarasiewicz** [Kunstmaan/KunstmaanBundlesCMS#497]
Hello,

I;m not able to generate a bundle with `kuma:generate:bundle`. I receive the following output in the terminal:

>[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
>Unrecognized option "admin_password" under "kunstmaan_admin"  

This appears after cloning the repository and providing default configuration for project name, etc.

What might be the problem here?

**Comment by Devolicious** [comment]
Hi,

You're probably using the master version of the standard edition instead of the tagged 3.1.2 version. admin_password is a new config var that will be available in the next release of the BundlesCMS. So your options are to use StandardEdition:3.1.2 & BundlesCMS:3.1.2 or StandardEdition:master & BundlesCMS:master

Happy coding!

**Comment by ltarasiewicz** [comment]
Actually, I followed the instruction at  "http://bundles.kunstmaan.be/documentation/installation" and executed `composer create-project -s dev kunstmaan/bundles-standard-edition myprojectname`.

Does that mean that I should not use composer to set up a Kunstmaan CMS project?

**Comment by Devolicious** [comment]
No, you should use composer to create a new project but the -s dev flag means that you're installing a dev version (aka master branch) of the standard edition. If you leave out the -s dev flag it will use the latest tagged version of the standard edition which is the correct one

**Comment by ltarasiewicz** [comment]
Thanks you for help
