### ISSUE TITLE
Delete media items using media manager

### ISSUE THREAD

**Issue by jeroenjans** [Kunstmaan/KunstmaanBundlesCMS#624]
When you delete media items using the media manager the media item gets the deleted flag.
The problem here is that the media is still physically available on the server and used for existing pageparts.

Ideally the media should also be deleted from the disk to prevent the unused media items from piling up.

A possible solution could be to check if any pageparts are using the media item when you're trying to delete the media item.
- If the media item has no linked pageparts it can be deleted.
- If the media item does have relations to pageparts the user should get a notification that tells him to remove the releations before trying to delete the media item.

**Comment by krispypen** [comment]
I don't think deleting the files from disk is the most ideally, because then we would have a lot of broken images.

Solution 1:
It can be a configuration to delete files when deleting the entities. (but default set to false)

Solution 2: 
Save every "used location" in a list in the media item, so we can check if those entities still exists. But how would you show the list then.... the toString of that entities... pageparts are just one possible reference.  and if an homepage has 60 versions, this list will be very long and the media is maybe not used on the latest version. So this solution needs some workout before implementation can start.

**Comment by jockri** [comment]
There is a command to remove the deleted media from the filesystem: kuma:media:clean-deleted-media 
You can run it in a cronjob if you want.
