### ISSUE TITLE
[MenuBundle][MultiDomainBundle] No MultiDomain support available for menu's

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#686]
I noticed it is not possible yet to create a menu for each host using MultiDomainBundle #633.

**Comment by roderik** [comment]
This seems like a good addition, PR welcome.

@jockri is there a workaround for now?

**Comment by jockri** [comment]
Currently, a menu is created for each locale. So if you have multiple domains with different locales, there should be no problem.

If you have different domains with the same locale (eg. domain.com/nl, domain.com/en, domain.net/nl, domain.net/en), then the menu for a locale is shared on both domains. In most cases this is also not a problem because if you use internal link `/nl/contact` for example, it will work on both domains.

Can you give me a use case that is not covered for the moment?

**Comment by yoshz** [comment]
The locale scope is indeed the same. But when you have a different hosts and different trees the menu's could be different as wel.
Our usecase on the moment is a site with a different pagetree using the same templating as the main site. 
One solution is the create different menu's for each site. The other solution is make the MenuBundle host aware, as you would expect when you change host in the admin. The addition of the domain property would probably the easy fix, just as you have done with the redirect module.

**Comment by jockri** [comment]
Cleaning up old issues
